### PR TITLE
Fix incorrect package name in README (#2)

### LINKED ISSUE #2: not on NPM
Titel says it all :)

Went here because of this comment: https://github.com/tailwindlabs/tailwindcss/issues/1232#issuecomment-1151409658

### PR DESCRIPTION
**Pull request by SebHex**
Closes #2

### CODE REVIEW

**Comment by bokub** [comment]
@TheDutchCoder up !

**Comment by bokub** [comment]
Thanks @TheDutchCoder ! And thanks for this module, it's really useful

**Comment by TheDutchCoder** [comment]
No problem!

Didn't even remember I forked this at some point 😅

**Comment by bokub** [comment]
Is this a fork of [this](https://github.com/jesstech/postcss-rem-to-pixel)? or [this](https://github.com/cuth/postcss-pxtorem) ?

Do you remember the difference between your fork and the original projects?

**Comment by TheDutchCoder** [comment]
Actually it might not have been a direct fork. I think I wrote it from scratch 🤔

**Pull request merged**
